nombreEvento: OTSO Media Maratón Getxo
fecha: 4 de abril de 2027
lugarSalida: Los Chopos Etorbidea 60, Getxo (Bizkaia)
horaSalida: "9:00"
subtitulo: Tres distancias — 5K, 10K y Media Maratón — en un recorrido totalmente llano por los monumentos más emblemáticos de Getxo.
enlaceInscripcion: https://inscripcion.kirolprobak.com/inscripcion/iv-otso-media-maraton-getxo-otso-getxoko-maratoi-erdia/?lang=es
